name: test-creation
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - fire=0.6.0
  - jupyter-book=0.15
  - jupyterlab=4.0
  - langchain=0.1.16
  - pandas=2.2.2
  - pip=24.0
  - pypandoc=1.6.3
  - python=3.12
  - python-dotenv=1.0.1
  - ruamel.yaml=0.18.6
  - tectonic=0.15.0
  - tqdm=4.66.4
  - scipy=1.13
  - pip:
    - distro==1.9.0
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - langchain-openai==0.1.6
    - openai==1.26.0
    - regex==2024.4.28
    - tiktoken==0.6.0
