name: test-creation
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - accessible-pygments=0.0.4=pyhd8ed1ab_0
  - aiohttp=3.9.5=py312he37b823_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alabaster=0.7.16=pyhd8ed1ab_0
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h02f2b3b_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312h9f69965_1
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2024.2.2=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py312h8e38eb3_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dataclasses-json=0.6.5=pyhd8ed1ab_0
  - debugpy=1.8.1=py312h20a0b95_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.17.1=py312h81bd7bf_5
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - fire=0.6.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - frozenlist=1.4.1=py312he37b823_0
  - greenlet=3.0.3=py312h20a0b95_0
  - idna=3.7=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py312h81bd7bf_3
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
  - jupyter-book=0.15.1=pyhd8ed1ab_0
  - jupyter-cache=0.6.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h81bd7bf_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.0.13=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.1=pyhd8ed1ab_0
  - krb5=1.21.2=h92f50d5_0
  - langchain=0.1.16=pyhd8ed1ab_0
  - langchain-community=0.0.36=pyhd8ed1ab_0
  - langchain-core=0.1.50=pyhd8ed1ab_0
  - langchain-text-splitters=0.0.1=pyhd8ed1ab_0
  - langsmith=0.1.54=pyhd8ed1ab_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - libblas=3.9.0=22_osxarm64_openblas
  - libcblas=3.9.0=22_osxarm64_openblas
  - libcxx=17.0.6=h5f092b4_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - liblapack=3.9.0=22_osxarm64_openblas
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.45.3=h091b4b1_0
  - libzlib=1.2.13=h53f4e23_5
  - linkify-it-py=2.0.3=pyhd8ed1ab_0
  - llvm-openmp=18.1.5=hde57baf_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312he37b823_0
  - marshmallow=3.21.2=pyhd8ed1ab_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdit-py-plugins=0.4.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - multidict=6.0.5=py312h670c8ac_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - myst-nb=0.17.2=pyhd8ed1ab_0
  - myst-parser=0.18.1=pyhd8ed1ab_0
  - nbclient=0.7.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h078ce10_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.26.4=py312h8442bc7_0
  - openssl=3.3.0=h0d3ecfb_0
  - orjson=3.10.3=py312h552d48e_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py312he37b823_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pybtex-docutils=1.0.3=py312h81bd7bf_1
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.7.1=pyhd8ed1ab_0
  - pydantic-core=2.18.2=py312hbdaf6d9_0
  - pydata-sphinx-theme=0.15.2=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyobjc-core=10.2=py312h9d22092_0
  - pyobjc-framework-cocoa=10.2=py312h9d22092_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.3=h4a7b5fc_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h02f2b3b_1
  - pyzmq=26.0.3=py312hfa13136_0
  - readline=8.2=h92ec313_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.18.1=py312h552d48e_0
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=5.0.2=pyh6c4a22f_0
  - sphinx-book-theme=1.0.1=pyhd8ed1ab_0
  - sphinx-comments=0.0.3=pyh9f0ad1d_0
  - sphinx-copybutton=0.5.2=pyhd8ed1ab_0
  - sphinx-design=0.3.0=pyhd8ed1ab_0
  - sphinx-external-toc=0.3.1=pyhd8ed1ab_1
  - sphinx-jupyterbook-latex=0.5.2=pyhd8ed1ab_0
  - sphinx-multitoc-numbering=0.1.3=pyhd8ed1ab_0
  - sphinx-thebe=0.2.1=pyhd8ed1ab_0
  - sphinx-togglebutton=0.3.2=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.8=pyhd8ed1ab_0
  - sphinxcontrib-bibtex=2.5.0=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.5=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - sqlalchemy=2.0.30=py312h7e5086c_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tenacity=8.2.3=pyhd8ed1ab_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py312he37b823_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.4=py312he37b823_0
  - zeromq=4.3.5=h5119023_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
      - distro==1.9.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - langchain-openai==0.1.6
      - openai==1.26.0
      - regex==2024.4.28
      - tiktoken==0.6.0
      - tqdm==4.66.4
