name: test-creation
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - jupyter-book=0.15
  - jupyterlab=4.0
  - pip=24.0
  - python=3.12
  - python-dotenv=1.0.1
  - fire=0.6.0
  - langchain=0.1.16
  - ruamel.yaml=0.18.6
  - pip:
    - distro==1.9.0
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - langchain-openai==0.1.6
    - openai==1.26.0
    - regex==2024.4.28
    - tiktoken==0.6.0
    - tqdm==4.66.4
